set-option -g default-shell /opt/homebrew/bin/fish
set-option -g default-command /opt/homebrew/bin/fish

set -g history-limit 10000
set -g allow-rename off
set -g status-style 'bg=default,fg=colour12'

set-window-option -g mode-keys vi
set -g set-clipboard on
set -g mouse on

bind-key -T copy-mode-vi Enter send-keys -X copy-pipe "pbcopy" \; send-keys -X cancel
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "pbcopy" \; send-keys -X cancel

bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

setw -g window-status-current-format "#[fg=colour235,bg=colour105,bold] #I:#W#F "
set -g status-right '#(echo "#{pane_current_path}" | sed "s|^$HOME|~|; s|\(\.\{0,1\}[^/]\)[^/]*/|\1/|g") | %H:%M '
